"""empty message

Revision ID: c22c540436ec
Revises: 
Create Date: 2024-10-20 13:07:04.988005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22c540436ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_blog',
    sa.Column('title', sa.String(length=200), nullable=False, comment='博客标题'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作者ID'),
    sa.Column('is_draft', sa.Boolean(), nullable=True, comment='是否为草稿'),
    sa.Column('detail_id', sa.Integer(), nullable=True, comment='详情内容ID'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_blog_detail',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('blog_id', sa.Integer(), nullable=False, comment='博客ID，唯一，关联博客表'),
    sa.Column('abstract', sa.String(length=500), nullable=True, comment='博客摘要'),
    sa.Column('content', sa.Text(), nullable=False, comment='博客内容'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blog_id')
    )
    op.create_table('tbl_blog_tags',
    sa.Column('blog_id', sa.Integer(), nullable=False, comment='博客ID'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='标签ID'),
    sa.PrimaryKeyConstraint('blog_id', 'tag_id')
    )
    op.create_table('tbl_category',
    sa.Column('name', sa.String(length=100), nullable=True, comment='分类名称'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_role',
    sa.Column('name', sa.String(length=100), nullable=False, comment='角色名称'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tbl_tag',
    sa.Column('name', sa.String(length=100), nullable=False, comment='标签名称'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_user',
    sa.Column('username', sa.String(length=100), nullable=False, comment='用户名'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('password', sa.String(length=200), nullable=False, comment='用户密码'),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=200), nullable=False, comment='用户邮箱'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='性别'),
    sa.Column('location', sa.String(length=100), nullable=True, comment='位置/地址'),
    sa.Column('birthdate', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('avatar', sa.String(length=200), nullable=True, comment='头像URL'),
    sa.Column('signature', sa.String(length=200), nullable=True, comment='个性签名'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_user')
    op.drop_table('tbl_tag')
    op.drop_table('tbl_role')
    op.drop_table('tbl_category')
    op.drop_table('tbl_blog_tags')
    op.drop_table('tbl_blog_detail')
    op.drop_table('tbl_blog')
    # ### end Alembic commands ###
